service:
  name: mongo-backup-scheduler

plugins:
  - serverless-webpack

custom:
  #region can be sent as CLI param
  region: ${opt:region, 'us-west-2'}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${opt:bucket}/*"
  #aws local profile can be sent as CLI param
  profile: ${opt:profile, 'default'}
  environment:
    SERVICE_NAME: ${self:service.name}
    MONGO_URI: ${opt:mongo-uri}
    AWS_S3_DUMP_BUCKET: ${opt:bucket}
    REGION: ${self:custom.region}

functions:
  backup:
    handler: src/mongo.backup
    events:
      - schedule: 
          name: ${self:service.name}-Scheduler
          # you can change the rate here
          rate: cron(0 12 * * ? *)

resources:
  Resources:
    DumpBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:bucket}
        LifecycleConfiguration:
          Rules:
          - Id: GlacierRule
            Status: Enabled
            # you can change expiration days here
            ExpirationInDays: '180'
            Transitions:
              # transition to glacier can be changed here
              - TransitionInDays: '7'
                StorageClass: Glacier